#
# MIT License
#
# Copyright (c) 2024 Václav Kubernát
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: "clang-tidy-cache for GitHub Actions"
description: "Run a linter on all changed files"
inputs:
  key:
    description: "An additional key for the ctcache"
    required: false
    default: ${{ github.job }}

runs:
  using: "composite"
  steps:
    - name: Install ctcache
      run: |
        CTCACHE_REF=e70da77cb867d74ccadce3f3c5862fc9cf4d22a7
        curl --location "https://github.com/matus-chochlik/ctcache/archive/${CTCACHE_REF}.tar.gz" | tar --extract --to-stdout --gzip --file - "ctcache-${CTCACHE_REF}/clang-tidy-cache" | sudo tee /usr/bin/clang-tidy-cache > /dev/null
        sudo chmod +x /usr/bin/clang-tidy-cache
        echo CTCACHE_DIR='${{github.workspace}}/.ctcache' >> "$GITHUB_ENV"
        echo "CTCACHE_NOW=$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")" >> $GITHUB_ENV
      shell: bash

    - name: Setup clang-tidy cache
      uses: actions/cache@v4
      with:
        key: ctcache-${{ inputs.key }}-${{ env.CTCACHE_NOW }}
        path: ${{env.CTCACHE_DIR}}
        restore-keys: ctcache-${{ inputs.key }}-

branding:
  icon: "archive"
  color: "gray-dark"
